# backend/security/migrations/0001_initial.py
# Назначение: первая миграция для приложения security. Путь: backend/security/migrations/0001_initial.py.
# Изменения: создание модели AdminGate.
# Generated by Django 5.2.5 on 2025-08-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdminGate",
            fields=[
                (
                    "singleton_id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("current_slug", models.CharField(db_index=True, max_length=64)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
