# Generated by Django 5.2.5 on 2025-08-15 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='portfolio/')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
            ],
        ),
        migrations.AddField(
            model_name='servicesection',
            name='icon',
            field=models.CharField(blank=True, help_text='CSS-класс или ссылка на иконку', max_length=100),
        ),
    ]
